#ifndef FEATURE_KEYCODES_H
#define FEATURE_KEYCODES_H

#include "keycodes.h"

enum feature_keycodes {
    FEATURE_KEYCODES = QK_PROGRAMMABLE_BUTTON_1,
    // LEADER HASH KEY
    FT_LEADER_HASH_1,
    FT_LEADER_HASH_2,
    FT_LEADER_HASH_3,
    // RAW MODIFIER
    FT_RAW_MOD,
    // DYNAKEY
    FT_DYNAKEY_1,
    FT_DYNAKEY_2,
    FT_DYNAKEY_3,
    FT_DYNAKEY_4,
    // COUNTER KEYS
    COUNTER_TARE,
    COUNTER_INCR,
    COUNTER_DECR,
    COUNTER_VALUE,
    // ALPHANUMERIC HASH
    FT_ALPHANUMERIC_HASH,
    // ALT TAB
    FT_ALT_TAB,
};

enum feature_aliases {
    // LEADER HASH KEY
    LHASH1 = FT_LEADER_HASH_1,
    LHASH2 = FT_LEADER_HASH_2,
    LHASH3 = FT_LEADER_HASH_3,
    // RAW MODIFIER
    MDRAW = FT_RAW_MOD,
    // DYNAKEY
    DYNA1 = FT_DYNAKEY_1,
    DYNA2 = FT_DYNAKEY_2,
    DYNA3 = FT_DYNAKEY_3,
    DYNA4 = FT_DYNAKEY_4,
    // COUNTER KEYS
    XTARE = COUNTER_TARE,
    XINCR = COUNTER_INCR,
    XDECR = COUNTER_DECR,
    XVALU = COUNTER_VALUE,
    // ALPHANUMERIC HASH
    AHASH = FT_ALPHANUMERIC_HASH,
    // ALT TAB
    ATAB = FT_ALT_TAB,
};

#endif